### PR TITLE
Fixed connection strings

### PR DESCRIPTION
**Pull request by makeSmartio**
Updated connection strings per Nextion HMI Protocol documentation. https://nextion.itead.cc/2017/12/08/nextion-hmi-upload-protocol-v1-1/

### CODE REVIEW

**Comment by Onno-Dirkzwager** [comment]
@Nredor this PR was discussed here: #5

**Comment by Onno-Dirkzwager** [comment]
@Nredor,
I can confirm the suggested PR also works for me on a basic 2.4 (I thought suggested changes might be enhanced version only...)

And I also found out about how we came to use a different send command:
- We based our work on [protocol v1.0](https://nextion.ca/documentation/nextion-upload-protocol-v1-0/)
command-> connect
- And when trying to help @makeSmartio #5 I sent him to [protocol v1.1](https://nextion.itead.cc/2017/12/08/nextion-hmi-upload-protocol-v1-1/) 
Where he found out the docs now recommend:
command-> DRAKJHSUYDGBNCJHGJKSHBDNÿÿÿ
command-> connectÿÿÿ
command-> ÿÿconnectÿÿÿ

**Comment by Onno-Dirkzwager** [comment]
@makeSmartio 
After further testing it seems that the esp8266 (software serial) depending on the core version needs the old commands... Ill have to do more testing. Just wanted to make sure @Nredor does not send out a new release yet...

**Comment by Onno-Dirkzwager** [comment]
Nextion esp8266 (softwareserial)
--------------------------------
core 2.4.1	| new commands | success
core 2.4.1	| old commands | success

core 2.4.2	| new commands | failed	|	get baudrate error
core 2.4.2	| old commands | succes

core 2.5.0	| new commands | failed	|	get baudrate error
core 2.5.0	| old commands | succes

core 2.5.1	| new commands | succes
core 2.5.1	| old commands | succes

core 2.5.2	| new commands | succes
core 2.5.2	| old commands | succes

Well that were some what confusing results.  Did al tests 2-3 time to be sure.
@Nredor I think we should reccommend 2.5.1 and higher for esp8266 users.

**Comment by Nredor** [comment]
I'll add the suggestiong about the core version to documentation. Thanks!

**Comment by Onno-Dirkzwager** [comment]
@Nredor Great and thankyou.
@makeSmartio Congratulations with your first PR!

**Pull request merged**
